# Config file for automatic testing at travis-ci.org

dist: trusty
sudo: required
language: python
python: 3.6
group: deprecated-2017Q3
services:
  - postgresql

addons:
  postgresql: "9.4"

env:
  - TOX_ENV=py36-django-111
  - TOX_ENV=py36-django-20

matrix:
  fast_finish: true

install: pip install -r requirements-test.txt

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV

deploy:
  provider: pypi
  user: $PYPI_USER
  password:
    secure: $PYPI_PASSWORD
  on:
    repo: Flickswitch/django-auditlog
    branch: stable
    condition: $TOX_ENV = py36-django-20
