# Generated by Django 3.0.8 on 2020-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0009_auto_20181207_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp'),
        ),
    ]
